apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-service
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Chart.Version }}"
  ports:
    - name: postgres
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      
  
