apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.storage.name }}-pvc
spec:
  accessModes:
    - {{ .Values.database.storage.accessMode }}
  storageClassName: {{ .Values.database.storage.className }}
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
