apiVersion: v2
name: services
type: application
version: 1.0.0
dependencies:
  - name: service
    version: 1.0.0
    alias: service-gateway
  - name: service
    version: 1.0.0
    alias: service-loyalty
  - name: service
    version: 1.0.0
    alias: service-payment
  - name: service
    version: 1.0.0
    alias: service-reservation
