version: '3'
services:
  api:
    image: person-service:latest
    container_name: person-service
    restart: on-failure
    depends_on:
      - postgres
  postgres:
    image: postgres:13.4-alpine
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

volumes:
  db-data:
