version: "3"
services:
  postgres:
    image: library/postgres:13.4-alpine
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - ${DB_PORT}:${DB_PORT}
  postgres-admin:
    image: dpage/pgadmin4:latest
    container_name: postgres-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - postgres
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
volumes:
  db-data:
