{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: {{ .Chart.Name }}
      port:
        number: {{ .Values.port.external }}
  rules:
    - host: open-api.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.port.external }}
{{- end }}
